spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot3_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson: # ?????
    date-format: yyyy-MM-dd HH:mm:ss # ????
    time-zone: GMT+8 # ??

# mp ??
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml # ??mapper????
  type-aliases-package: com.xjy.week06.api.entity # ??entity
  configuration:
    map-underscore-to-camel-case: true  # ??????
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl # ??sql